name: perfect_elegance
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_svg: ^2.0.15
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  lottie: ^3.1.3
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  pinput: ^5.0.0
  intl: ^0.19.0
  connectivity_plus: ^6.1.1
  syncfusion_flutter_charts: ^28.1.36
  flutter_widget_from_html: ^0.15.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png"
  adaptive_icon_background: "#4546BE"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lotties/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 800
